name: text_scroller
description: TextScroller Flutter widget adds text auto-scrolling functionality (marquee text).
version: 0.0.1
repository: https://github.com/yurii-khi/text_scroller

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
